CREATE DATABASE housing;

USE housing;

CREATE TABLE people (
    PEO_CPF CHAR(11) PRIMARY KEY NOT NULL,
    PEO_NAME VARCHAR(140) NOT NULL,
    PEO_PHONE VARCHAR(11) NOT NULL,
    PEO_EMAIL VARCHAR(140) NOT NULL
);

CREATE TABLE houses (
    HOU_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    HOU_TITLE VARCHAR(140) NOT NULL,
    HOU_TIPO VARCHAR(32) NOT NULL,
    HOU_PRICE DECIMAL(10, 2) NOT NULL,
    HOU_PEO_CPF CHAR(11) NOT NULL,
    CONSTRAINT FK_HOUSES_PEOPLE FOREIGN KEY (HOU_PEO_CPF) REFERENCES people(PEO_CPF) ON DELETE CASCADE
);
